name: Shell commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    steps:
      
      - name: echo a string
        run: |
           echo "TEST: ${KENNY}"
           echo "GITHUB_ACTOR: ${GITHUB_ACTOR}"
      - name: multiline script
        run: |
          python3 -V
          touch my_file_with_workflow.py
          ls -l
